FROM busybox

# Instala o wget
RUN wget -O dataguard.jar https://raw.githubusercontent.com/EigTech-Solutions/Java/main/target/dataguard-1.0-SNAPSHOT-jar-with-dependencies.jar
CMD ["java", "-jar", "dataguard.jar"]
