version: '3'

services:
  jarDataGuard:
    image: openjdk:11-jre-slim
    working_dir: /app
    command: java -jar dataguard.jar

    # Adicionando o bloco 'build' para realizar o download do JAR
    build:
      context: .
      dockerfile: Dockerfile-jar

    # Outras configurações necessárias para o seu serviço
